### ISSUE TITLE
Pool cover

### ISSUE THREAD

**Issue by jaqpot** [lostcontrol/poupool#4]
## Pool cover type
T&A Premium Clean Profile Alu Look (solar) 4.08x9.80 m

## Drive system
175 Nm AC motor with pulse counter

## Control electronics
- AC Relays to control motor rotation with 24VDC input (in main electrical panel)
- Arduino in the control electrical panel
- Pulse counter connected to the Arduino

## RPi
- serial interface with Arduino (USB connector)

## Arduino
-...

**Comment by lostcontrol** [comment]
We need to have 3 buttons on the Arduino to manually control the cover and set the endpoint(s). Possible with the current electrical panel? Otherwise I can print a case and we can put the Arduino next to the motor. Also, is power with USB enough for the Arduino system or do we need something special for the pulse counter?

**Comment by lostcontrol** [comment]
We could use the same Arduino for both cover and water counter. 1000 Hz sounds like a lot for that motor no? Anyway, the µC should be able to handle that without any problem. We can do the counting [in hardware](http://sphinx.mythic-beasts.com/~markt/ATmega-timers.html). I hope the signal is clean enough.

Also it would be easier to use the USB serial connection directly instead of I2C for that matter.
